openapi: 3.0.1
info:
  title: Mark Harrison Colors API
  description: Colors API this one doesn't work
  termsOfService: https://github.com/markharrison/ColorsAPI/blob/master/LICENSE
  contact:
    name: Mark Harrison
    url: https://github.com/markharrison/ColorsAPI
    email: mark.colorsapi@harrison.ws
  license:
    name: Use under MIT License
    url: https://github.com/markharrison/ColorsAPI/blob/master/LICENSE
  version: '1.0'
servers:
  - url: https://brd-apim-dev.azure-api.net
paths:
  /colors:
    get:
      tags:
        - Colors
      summary: Get colors
      description: Returns all colors.
      operationId: GetColors
      responses:
        '200':
          description: Success - returns list of colors
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ColorsItem'
              example:
                - id: 0
                  name: string
                  data: string
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ColorsItem'
              example:
                - id: 0
                  name: string
                  data: string
    post:
      tags:
        - Colors
      summary: Update / create colors
      description: Updates colors - creates color if it doesn't exist
      operationId: UpdateColors
      requestBody:
        description: Colors to update
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ColorsItem'
            example:
              - id: 0
                name: string
                data: string
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ColorsItem'
            example:
              - id: 0
                name: string
                data: string
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ColorsItem'
            example:
              - id: 0
                name: string
                data: string
      responses:
        '201':
          description: Success - colors updated/created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '422':
          description: Unprocessable Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
    delete:
      tags:
        - Colors
      summary: Delete colors
      description: Deletes all colors.
      operationId: DeletesColors
      responses:
        '204':
          description: Success - all colors deleted
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
  '/colors/{colorId}':
    get:
      tags:
        - Colors
      summary: Get color by id
      description: 'Returns color specified by {colorId} (must be between 1 and 1000).'
      operationId: GetColorById
      parameters:
        - name: colorId
          in: path
          description: Format - int32. Id of Color to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success - returns color
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
        '422':
          description: Unprocessable Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
    post:
      tags:
        - Colors
      summary: Update / create color by id
      description: 'Updates color specified by {colorId} (must be between 1 and 1000);  use {colorId} = 0 to insert new color'
      operationId: UpdateColorById
      parameters:
        - name: colorId
          in: path
          description: Format - int32. Id of Color to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Colors to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ColorsItem'
            example:
              id: 0
              name: string
              data: string
          text/json:
            schema:
              $ref: '#/components/schemas/ColorsItem'
            example:
              id: 0
              name: string
              data: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/ColorsItem'
            example:
              id: 0
              name: string
              data: string
      responses:
        '201':
          description: Success - color created/updated
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '422':
          description: Unprocessable Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
    delete:
      tags:
        - Colors
      summary: Delete color by id
      description: 'Deletes color specified by {colorId} (must be between 1 and 1000).'
      operationId: DeleteColorById
      parameters:
        - name: colorId
          in: path
          description: Format - int32. Id of Color to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Success - color deleted
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '422':
          description: Unprocessable Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
  /colors/findbyname:
    get:
      tags:
        - Colors
      summary: Get color by name
      description: 'Returns color specified by {colorName} '
      operationId: GetColorByName
      parameters:
        - name: colorName
          in: query
          description: Name of Color to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success - returns color
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
  /colors/random:
    get:
      tags:
        - Colors
      summary: Get random color
      description: Returns random color.
      operationId: GetRandomColor
      responses:
        '200':
          description: Success - returns random color
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: string
                title: string
                status: 0
                detail: string
                instance: string
  /colors/reset:
    post:
      tags:
        - Colors
      summary: Reset colors
      description: Reset colors to default.
      operationId: ResetColors
      responses:
        '201':
          description: Success - colors reset
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example: ''
            application/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
            text/json:
              schema:
                $ref: '#/components/schemas/ColorsItem'
              example:
                id: 0
                name: string
                data: string
components:
  schemas:
    ColorsItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        data:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]